### ISSUE TITLE
Edit Article Title Endpoint

### ISSUE THREAD

**Issue by wlhunter00** [jasonren5/contact-tracer#124]
Firebase function to update the title of the article

Check out hunter/106-edit-article-ui

TODO: Line 70 app\src\components\Articles\EditArticles\EditHeaderText.js

Mirror what we did for updating a section's end point. We need to handle merge requests similarly.

**Comment by jasonren5** [comment]
Mirroring updating section would require database 'schema' change -- we don't currently store any history for titles, nor is there really an easy way to do this. Sections need to be tied to titles somehow, or else we get weird messes where we roll back to a title that current sections do not support. 

How necessary is it to edit titles? News sites generally have it, but it is worthy to note imo that Reddit (you know, a site that relies on user generated titles and content) does not allow you to edit titles.

If we decide that this is a feature that we actually want, I will likely opt to implement a more naive implementation unless we decide it's absolutely necessary to change 'schema'.

**Comment by wlhunter00** [comment]
100% needed. Maybe we transition titles/headings to be something that is rendered as a section type.

We should do a title type, and then a heading type (separate). The article page should then have to read in that the type is a title, and render it and the edit components properly. This would require a decent overhaul, probably best to do it on a new branch
