### ISSUE TITLE
Remove Section Firebase Function

### ISSUE THREAD

**Issue by wlhunter00** [jasonren5/contact-tracer#126]
We need a firebase function to remove a section from an article.

This should also be extended so that if someone edits an section so that it is empty, it deletes that section.

Check out hunter/106-edit-article-ui

TODO: Line 128
app\src\components\Sections\EditSectionText.js

**Comment by jasonren5** [comment]
How should we handle deleting sections? I don't think it's right that we should be deleting all the history of that section, which could be valuable to an article. I think a better way to handle deleting sections would be to simply not render any section that has an empty body on the front end -- that way the history of that section is preserved to editors.
