### ISSUE TITLE
Generate new articles

### ISSUE THREAD

**Issue by jbraunschweiger** [jasonren5/contact-tracer#91]
This should be a backend function that is triggered every XX amount of time (to be decided later). It should contact a News API and create new articles based on the top headlines. Part of this ticket is finding the proper API for our first version of generating articles.

**Comment by jasonren5** [comment]
I'll be using the News API -- free access lasts for one month starting from now.

**Comment by jasonren5** [comment]
API Key has been added to GItHub Secrets

**Comment by jasonren5** [comment]
API key should be deployed to firebase with name 'news_api', and should be accessible within functions through the following documentation: https://firebase.google.com/docs/functions/config-env
